/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author halit
 */
public class BasitHesapMakinesi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BasitHesapMakinesi.class.getName());

    /**
     * Creates new form BasitHesapMakinesi
     */
    public BasitHesapMakinesi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toplama_button = new javax.swing.JButton();
        birinci_sayi_label = new javax.swing.JLabel();
        ikinci_sayi_label = new javax.swing.JLabel();
        cikarma_button = new javax.swing.JButton();
        carpma_button = new javax.swing.JButton();
        bolme_button = new javax.swing.JButton();
        sonuc_label = new javax.swing.JLabel();
        birinci_sayi_field = new javax.swing.JTextField();
        ikinci_sayi_field = new javax.swing.JTextField();
        sonuc_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toplama_button.setText("+");
        toplama_button.addActionListener(this::toplama_buttonActionPerformed);

        birinci_sayi_label.setText("Birinci Sayı: ");

        ikinci_sayi_label.setText("İkinci Sayı: ");

        cikarma_button.setText("-");
        cikarma_button.addActionListener(this::cikarma_buttonActionPerformed);

        carpma_button.setText("*");
        carpma_button.addActionListener(this::carpma_buttonActionPerformed);

        bolme_button.setText("/");
        bolme_button.addActionListener(this::bolme_buttonActionPerformed);

        sonuc_label.setText("Sonuç : ");

        sonuc_field.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bolme_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cikarma_button, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(carpma_button, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(toplama_button, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(birinci_sayi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ikinci_sayi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(sonuc_label, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(birinci_sayi_field)
                            .addComponent(ikinci_sayi_field)
                            .addComponent(sonuc_field, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birinci_sayi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birinci_sayi_field))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ikinci_sayi_label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ikinci_sayi_field, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sonuc_label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sonuc_field, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cikarma_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(toplama_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carpma_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bolme_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toplama_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toplama_buttonActionPerformed
        int birinci_sayi = Integer.valueOf(this.birinci_sayi_field.getText());
        int ikinci_sayi = Integer.valueOf(this.ikinci_sayi_field.getText());
        
        this.sonuc_field.setText(String.valueOf(birinci_sayi + ikinci_sayi));
    }//GEN-LAST:event_toplama_buttonActionPerformed

    private void cikarma_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikarma_buttonActionPerformed
        int birinci_sayi = Integer.valueOf(this.birinci_sayi_field.getText());
        int ikinci_sayi = Integer.valueOf(this.ikinci_sayi_field.getText());
        
        this.sonuc_field.setText(String.valueOf(birinci_sayi - ikinci_sayi));
    }//GEN-LAST:event_cikarma_buttonActionPerformed

    private void carpma_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carpma_buttonActionPerformed
        int birinci_sayi = Integer.valueOf(this.birinci_sayi_field.getText());
        int ikinci_sayi = Integer.valueOf(this.ikinci_sayi_field.getText());
        
        this.sonuc_field.setText(String.valueOf(birinci_sayi * ikinci_sayi));
    }//GEN-LAST:event_carpma_buttonActionPerformed

    private void bolme_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolme_buttonActionPerformed
        int birinci_sayi = Integer.valueOf(this.birinci_sayi_field.getText());
        int ikinci_sayi = Integer.valueOf(this.ikinci_sayi_field.getText());
        
        this.sonuc_field.setText(String.valueOf((double)birinci_sayi / ikinci_sayi));
    }//GEN-LAST:event_bolme_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BasitHesapMakinesi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField birinci_sayi_field;
    private javax.swing.JLabel birinci_sayi_label;
    private javax.swing.JButton bolme_button;
    private javax.swing.JButton carpma_button;
    private javax.swing.JButton cikarma_button;
    private javax.swing.JTextField ikinci_sayi_field;
    private javax.swing.JLabel ikinci_sayi_label;
    private javax.swing.JTextField sonuc_field;
    private javax.swing.JLabel sonuc_label;
    private javax.swing.JButton toplama_button;
    // End of variables declaration//GEN-END:variables
}
